---
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-cli

    working_directory: ~/shifter-wp-mu

    steps:
      - checkout

      - run:
          command: composer install
      - run: |
          env

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
