---
version: 2.1

orbs:
  php_lint:
    jobs:
      composer_install:
        executor: php_cli
        steps:
          - composer_install:
              name: composer_install
    commands:
      composer_install:
        steps:
          - run: composer install
    executors:
      php_cli:
        parameters:
          image_tag:
            type: string
            default: "7.3.5-cli"
        docker:
          - image: circleci/php:<<parameters.image_tag>>


workflows:
  build-test-deploy:
    jobs:
      - php_lint/composer_install:
          name: composer_install
